security:
    enable_authenticator_manager: true
    providers:
        oauth_users:
            id: App\Security\User\OAuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: oauth_users
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
