security:
    providers:
        oauth_users:
            id: App\Security\User\OAuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: oauth_users
            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
