security:
    enable_authenticator_manager: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
