services:
    app:
        image: fabricon-app:local
        depends_on:
            - database
    web:
        image: fabricon-web:local
        ports:
            - 8000:80
        depends_on:
            - app
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: main
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: {}
