services:
    app:
        image: fabricon-app:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        environment:
            APP_ENV: dev
            OPCACHE_VALIDATE_TIMESTAMPS: 1
        volumes:
            - .:/var/www/html:rw,cached
        depends_on:
            - database
    web:
        image: fabricon-web:local
        build:
            args:
                ASSETS_IMAGE: fabricon-app:local
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8000:80
        depends_on:
            - app
        volumes:
            - ./public:/var/www/html/public:ro,delegated
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: main
        ports:
            - 5432
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: {}
