services:
    app:
        image: fabricon-app:local
        depends_on:
            - db
    web:
        image: fabricon-web:local
        ports:
            - 8000:80
        depends_on:
            - app
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: fabricon_password
            POSTGRES_USER: fabricon_user
            POSTGRES_DB: fabricon_db
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: {}
